services:
  db:
    image: postgres:16-alpine
    container_name: subscription_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: subscription_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
  caddy:
    image: caddy:alpine
    container_name: caddy_server
    restart: always
    ports:
      - "80:80" 
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Прокидываем конфиг
      - caddy_data:/data                 
      - caddy_config:/config
    depends_on:
      - app
  minio:
    image: quay.io/minio/minio:latest
    container_name: crm_minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API порт (для кода)
      - "9001:9001" # Консоль (для браузера)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    volumes:
      - ./minio_data:/data # Папка в корне проекта, где будут лежать файлы

volumes:
  postgres_data:
  caddy_data:
  caddy_config: